services:
    mosquitto:
        image: eclipse-mosquitto:1.6
        restart: unless-stopped
        ports:
            - "1883:1883"

    server:
        build: .
        restart: unless-stopped
        ports:
            - "3001:3001"
